# app/services/webauthn_service.py
#
# Wraps py_webauthn (webauthn==2.2.0) to generate and verify
# FIDO2/WebAuthn registration and authentication ceremonies.
#
# Design notes:
#   - Pure functions / static methods — no state, easy to test.
#   - challenge storage is stateless: the challenge bytes are embedded in a
#     short-lived JWT (challenge_token) signed with SECRET_KEY, so no extra
#     DB table is needed.
#   - All base64url encoding/decoding goes through webauthn's own helpers so
#     we stay consistent with the spec.

from __future__ import annotations

import base64
from typing import TYPE_CHECKING

import webauthn
from webauthn.helpers import bytes_to_base64url, base64url_to_bytes
from webauthn.helpers.structs import (
    AuthenticatorSelectionCriteria,
    ResidentKeyRequirement,
    UserVerificationRequirement,
    PublicKeyCredentialDescriptor,
    AuthenticatorTransport,
)
from webauthn.helpers.exceptions import (
    InvalidCBORData,
    InvalidRegistrationResponse,
    InvalidAuthenticationResponse,
)

from app.core.config import get_settings

if TYPE_CHECKING:
    from domains.auth.models import WebAuthnCredential
    from domains.users.models import User


class WebAuthnService:
    """
    Stateless service for FIDO2/WebAuthn ceremonies.

    All methods are class methods — instantiation not required.
    """

    # ---------------------------------------------------------------- #
    #  Registration                                                     #
    # ---------------------------------------------------------------- #

    @classmethod
    def generate_registration_options(
        cls,
        user: "User",
        existing_credentials: list["WebAuthnCredential"],
        challenge: bytes,
    ) -> dict:
        """
        Build PublicKeyCredentialCreationOptions for the client.

        Returns a JSON-serializable dict ready to pass to Passkey.register()
        on the React Native side.

        Args:
            user: The authenticated user registering a new passkey.
            existing_credentials: Already-registered credentials to exclude
                                   (prevents duplicate registration).
            challenge: 32 random bytes generated by the caller and embedded
                       in the challenge_token JWT.
        """
        settings = get_settings()

        exclude_credentials = [
            PublicKeyCredentialDescriptor(
                id=cred.credential_id,
                transports=[
                    AuthenticatorTransport(t) for t in (cred.transports or [])
                    if t in {e.value for e in AuthenticatorTransport}
                ],
            )
            for cred in existing_credentials
        ]

        opts = webauthn.generate_registration_options(
            rp_id=settings.WEBAUTHN_RP_ID,
            rp_name=settings.WEBAUTHN_RP_NAME,
            user_id=str(user.id).encode(),
            user_name=user.email,
            user_display_name=user.full_name or user.email,
            challenge=challenge,
            authenticator_selection=AuthenticatorSelectionCriteria(
                resident_key=ResidentKeyRequirement.REQUIRED,
                user_verification=UserVerificationRequirement.PREFERRED,
            ),
            exclude_credentials=exclude_credentials,
        )

        return webauthn.options_to_json(opts)

    @classmethod
    def verify_registration_response(
        cls,
        challenge: bytes,
        credential_response: dict,
    ) -> webauthn.VerifiedRegistration:
        """
        Verify the attestation returned by Passkey.register().

        Raises:
            InvalidAuthenticatorResponse: if verification fails (bad signature,
                                          wrong origin, replay, etc.)
        """
        settings = get_settings()

        registration_credential = webauthn.helpers.parse_registration_credential_json(
            credential_response
        )

        return webauthn.verify_registration_response(
            credential=registration_credential,
            expected_challenge=challenge,
            expected_rp_id=settings.WEBAUTHN_RP_ID,
            expected_origin=settings.WEBAUTHN_ORIGIN,
            require_user_verification=False,
        )

    # ---------------------------------------------------------------- #
    #  Authentication                                                   #
    # ---------------------------------------------------------------- #

    @classmethod
    def generate_authentication_options(
        cls,
        credentials: list["WebAuthnCredential"],
        challenge: bytes,
    ) -> dict:
        """
        Build PublicKeyCredentialRequestOptions for the client.

        Returns a JSON-serializable dict ready to pass to Passkey.authenticate().

        Args:
            credentials: The user's stored passkey credentials
                         (used to populate allowCredentials).
            challenge:   32 random bytes generated by the caller and embedded
                         in the challenge_token JWT.
        """
        settings = get_settings()

        allow_credentials = [
            PublicKeyCredentialDescriptor(
                id=cred.credential_id,
                transports=[
                    AuthenticatorTransport(t) for t in (cred.transports or [])
                    if t in {e.value for e in AuthenticatorTransport}
                ],
            )
            for cred in credentials
        ]

        opts = webauthn.generate_authentication_options(
            rp_id=settings.WEBAUTHN_RP_ID,
            challenge=challenge,
            allow_credentials=allow_credentials,
            user_verification=UserVerificationRequirement.PREFERRED,
        )

        return webauthn.options_to_json(opts)

    @classmethod
    def verify_authentication_response(
        cls,
        challenge: bytes,
        credential_response: dict,
        stored_credential: "WebAuthnCredential",
    ) -> webauthn.VerifiedAuthentication:
        """
        Verify the assertion returned by Passkey.authenticate().

        Raises:
            InvalidAuthenticatorResponse: if verification fails.
        """
        settings = get_settings()

        authentication_credential = webauthn.helpers.parse_authentication_credential_json(
            credential_response
        )

        return webauthn.verify_authentication_response(
            credential=authentication_credential,
            expected_challenge=challenge,
            expected_rp_id=settings.WEBAUTHN_RP_ID,
            expected_origin=settings.WEBAUTHN_ORIGIN,
            credential_public_key=stored_credential.public_key,
            credential_current_sign_count=stored_credential.sign_count,
            require_user_verification=False,
        )

    # ---------------------------------------------------------------- #
    #  Helpers                                                          #
    # ---------------------------------------------------------------- #

    @staticmethod
    def credential_id_to_b64(credential_id_bytes: bytes) -> str:
        """Convert raw credential_id bytes to base64url string for API responses."""
        return bytes_to_base64url(credential_id_bytes)

    @staticmethod
    def b64_to_credential_id(b64url: str) -> bytes:
        """Convert base64url string to raw credential_id bytes for DB lookup."""
        return base64url_to_bytes(b64url)
